name: Generate Pacman Animation with Theme Rotation

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # <-- Added timeout for safety
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Randomly select a theme
        id: random-theme
        run: |
          themes=("halloween" "matrix" "candyland")
          SELECTED_THEME=${themes[$RANDOM % ${#themes[@]}]}
          echo "Selected theme: $SELECTED_THEME"
          echo "theme=$SELECTED_THEME" >> $GITHUB_ENV

      - name: Set Theme Colors
        id: set-colors
        run: |
          if [ "${{ env.theme }}" == "halloween" ]; then
            echo "color_pacman=#FFA500" >> $GITHUB_ENV
            echo "color_ghost=#800080" >> $GITHUB_ENV
            echo "color_candy=#FF0000" >> $GITHUB_ENV
          elif [ "${{ env.theme }}" == "matrix" ]; then
            echo "color_pacman=#00FF00" >> $GITHUB_ENV
            echo "color_ghost=#FF00FF" >> $GITHUB_ENV
            echo "color_candy=#00FFFF" >> $GITHUB_ENV
          elif [ "${{ env.theme }}" == "candyland" ]; then
            echo "color_pacman=#FF69B4" >> $GITHUB_ENV
            echo "color_ghost=#FFD700" >> $GITHUB_ENV
            echo "color_candy=#00CED1" >> $GITHUB_ENV
          fi

      - name: Generate Pacman Graph based on Theme
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: BadarNawaz33
          theme: "auto"
          color_pacman: ${{ env.color_pacman }}
          color_ghost: ${{ env.color_ghost }}
          color_candy: ${{ env.color_candy }}
          ghost_count: 25
          pacman_speed: 5

      - name: Push Pacman SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
